### ISSUE TITLE
Manually Connecting to the Wifi (Keyboard Needed)

### ISSUE THREAD

**Issue by qwksilver** [Geektoolkit/DynaframeProIssues#10] opened 2022-10-02 17:56 UTC
A mouse will also make this easier.
originally from https://discord.com/channels/626204510422827028/953137212432711760/1025922964530663454

Steps after keyboard plugged in:
1. `esc`
2. `ctr-esc`, down arrow or mouse to preferences, then raspberry pi configuration.
3. setup wi-fi country, timezone, keyboard choices, and locale
4. `ctr-alt-t` (terminal)
5. type `comitup-cli` on terminal, and enter
6.  in comitup-cli you should have a list of numbers showing various lan-wifi availability
7.  choose the number  that matches your wi-fi then hit enter.
8.  type in wi-fi password (blank entry with no cursor movement)
9. check to see it's working, it will say STATE: `Connected`, and Connection: `Your Wifi Name Here`
10. exit with `q` <enter>

finally do this command `ifconfig wlan 0` and press enter.
it will come back and identify `inet:`  which will have your new ip address right there.
if that ip is NOT `10.41.0.1` then note yours down, and reboot with this last command.

`sudo reboot` <enter>

if it is `10.41.0.1` go back to step 5 and work your way down again, make sure password/security code is correct and capslock off etc.  if you have problems after a few tries, pop over to discord, and ask for help in on-topic.

**Comment by GaryLittlemore** [comment] 2022-10-07 09:10
I'm new here, reading the bit about heading over Discord and asking for help. I joined the Discord server, there doesn't seem to be a section where users can post for help, it seems to be all read-only.

**Comment by bdlou** [comment] 2022-10-07 11:44
Make sure you follow the steps in the #welcome channel.

**Comment by GaryLittlemore** [comment] 2022-10-07 12:59
Doh! TY bdlou

**Comment by jimholmesNZ** [comment] 2023-01-24 23:18
I'm located in New Zealand. I'm having problems getting the wifi to connect, I originally got the pi connected to my wifi (I used the connect to the dynaframe wifi and set with my phone) however it didn't reconnect after a reboot. 

Since then I've tried connecting to the dynaframe wifi navigating to the 10.41.0.1 page and entering my wifi credentials there, both with my phone and a Windows 10 laptop, no joy. I've also used these instructions to manually connect the wifi, same issue. 
No matter how many times I set my locale the Wifi country is never retained. I've tried using the raspberry pi configuration detailed here, and using sudo raspi-config. Neither survives a reboot, any ideas? I really don't want to have to use an Ethernet cable. Thanks.

I'm using build 61387c6.

**Comment by Geektoolkit** [comment] 2023-01-26 22:34
@jimholmesNZ I don't have a good answer here..yet. We are heads down reworking the wifi to rip out the system we were using because of the troubles it causes us and our users.  We expect to have an alpha out in the next week that will give you a way to setup the wifi manually, and without using the comitup system that is being used now.  It also is an update that restores the raspbian configuration for wifi, so that worst case you can set it up using raspbian.

I suspect you're hitting a bug in comitup which has caused us quite a bit of headaches.  I think it's great software for what it was designed for, but for the use we're trying to use it for it hasn't been ideal.

If you can wait till the next alpha, then you can connect an ethernet, update, then connect wifi and unplug the ethernet and should be golden.

**Comment by jimholmesNZ** [comment] 2023-01-27 03:51
@Geektoolkit thanks for the reply, I'm OK waiting for the new alpha. Is there anything I need to do to get access to the alpha when it becomes available? Thanks again.

**Comment by Geektoolkit** [comment] 2023-01-27 16:25
All you have to do is be an active Patreon and in the Discord. When you see the post then contact Qwksilver and he'll get you onboarded. Details will be in the Patreon post when it's ready

**Comment by jimholmesNZ** [comment] 2023-01-27 19:13
@Geektoolkit OK thanks.

**Comment by Geektoolkit** [comment] 2023-03-26 08:02
@jimholmesNZ  Following up here...there's a new beta that's gone out today, if you get a chance to try it can you let us know if this is better? if so please let us know and we'll close this out.

**Comment by jimholmesNZ** [comment] 2023-03-28 07:20
@Geektoolkit I've tried using the upgrade code and rebuilding the sd card from scratch, unfortunately neither options work. The dynaframe does not connect to my wifi unless I also have a wired ethernet connection. 

When connected to a wired ethernet connection the frame displays two ip addresses, when the wired connection is present I can access the frame on both ip addresses. When I disconnect the wired connection the frame displays only one ip address, however although it displays the address I cannot ping or connect via that address. If I press Escape and have a look at the wireless symbol in the top left corner it shows that it is connected and has a tick next to the correct SSID, however there is no connection.

**Comment by Geektoolkit** [comment] 2023-03-31 19:34
The device you're connecting from is also on that same wireless network right? Do the ips of the device you're connecting from and the frame ip match? I had that issue because I was in two different ip ranges

**Comment by jimholmesNZ** [comment] 2023-04-02 04:10
Yes the IP Address of the devices that I have tried to connect to the dynaframe are on the same IP address range. I tried the latest April release but no different.

**Comment by Geektoolkit** [comment] 2023-04-14 06:38
Resolving this. The April update makes this obsolete.

**Closed as completed by Geektoolkit** 2023-04-14 06:38 UTC
